INSERT INTO PUBLIC.CATEGORIES (NAME, DESCRIPTION) VALUES ('Mobile Phones', 'Мобильные телефоны');
INSERT INTO PUBLIC.CATEGORIES (NAME, DESCRIPTION) VALUES ('Microwaves', 'Microwaves');
INSERT INTO PUBLIC.CATEGORIES (NAME, DESCRIPTION) VALUES ('Fridges', 'Fridges, Freezers');
INSERT INTO PUBLIC.CATEGORIES (NAME, DESCRIPTION) VALUES ('Vacuum cleaner', 'Vacuum cleaner');
INSERT INTO PUBLIC.CATEGORIES (NAME, DESCRIPTION) VALUES ('TV', 'Television');

INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Motorola e775', 'A mobile phone is a portable telephone that can make and receive calls over a radio frequency link while the user is moving within a telephone service area. The radio frequency link establishes a connection to the switching systems of a mobile phone operator, which provides access to the public switched telephone network PSTN. Most modern mobile telephone services use a cellular network architecture, and therefore mobile telephones are often also called cellular telephones or cell phones.', 149.99, 'USD', 1, '/7ee7ff179c144dfa8245a3a09102ef46.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Motorola q11-11', 'Most modern mobile telephone services use a cellular network architecture, and therefore mobile telephones are often also called cellular telephones or cell phones. In addition to telephony, 2000s-era mobile phones support a variety of other services, such as text messaging, MMS, email, Internet access, short-range wireless communications', 99.99, 'USD', 1, '/04c08514939f4fd893a0807134cc1e22.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Siemens', 'Microwave ovens are popular for reheating previously cooked foods and cooking a variety of foods. They are also useful for rapid heating of otherwise slowly prepared cooking items, such as hot butter, fats, and chocolate. Unlike conventional ovens, microwave ovens usually do not directly brown or caramelize food, since they rarely attain the necessary temperatures to produce Maillard reactions. ', 199.99, 'USD', 2, '/9b1bd8e3e67e452cb9c4b7b9ca672c49.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Samsung', 'Comparative cooking method studies generally find that, if properly used, microwave cooking does not affect the nutrient content of foods to a larger extent than conventional heating, and that there is a tendency towards greater retention of many micronutrients with microwaving, probably due to the reduced preparation time.[35] Microwaving human milk at high temperatures is contraindicated, due to a marked decrease in activity of anti-infective factors.[', 249.99, 'USD', 2, '/46d2d6e2ac1c4b3d8f134db9903be6a1.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('LG', 'The first cooling systems for food involved using ice. Artificial refrigeration began in the mid-1750s, and developed in the early 1800s. In 1834, the first working vapor-compression refrigeration system was built. The first commercial ice-making machine was invented in 1854. In 1913, refrigerators for home use were invented. In 1923 Frigidaire introduced the first self-contained unit. The introduction of Freon in the 1920s expanded the refrigerator market during the 1930s.', 449.99, 'USD', 3, '/0dc581ae53dc4ba2ae2256eeeab88148.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Ariston', 'The first cooling systems for food involved using ice. Artificial refrigeration began in the mid-1750s, and developed in the early 1800s. In 1834, the first working vapor-compression refrigeration system was built. The first commercial ice-making machine was invented in 1854. In 1913, refrigerators for home use were invented. In 1923 Frigidaire introduced the first self-contained unit. The introduction of Freon in the 1920s expanded the refrigerator market during the 1930s.', 399.99, 'USD', 3, '/e9046aca5e534074a7643dc744c82222.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('LG R775', 'The dirt is collected by either a dustbag or a cyclone for later disposal. Vacuum cleaners, which are used in homes as well as in industry, exist in a variety of sizes and models small battery-powered hand-held devices, wheeled canister models for home use, domestic central vacuum cleaners, huge stationary industrial appliances that can handle several hundred litres of dust before being emptied, and self-propelled vacuum trucks for recovery of large spills or removal of contaminated soil. Specialized shop vacuums can be used to suck up both dust and liquids.', 79.99, 'USD', 4, '/98903a85d1634e17b394b49a518a03cc.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Samsung C700', 'The dirt is collected by either a dustbag or a cyclone for later disposal. Vacuum cleaners, which are used in homes as well as in industry, exist in a variety of sizes and models small battery-powered hand-held devices, wheeled canister models for home use, domestic central vacuum cleaners, huge stationary industrial appliances that can handle several hundred litres of dust before being emptied, and self-propelled vacuum trucks for recovery of large spills or removal of contaminated soil. Specialized shop vacuums can be used to suck up both dust and liquids.', 149.50, 'USD', 4, '/15355d87c88446b9afc9de4f8299ea99.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Samsung n110', 'A television set, more commonly called a television, TV, TV set, television receiver, or telly, is a device that combines a tuner, display, and loudspeakers for the purpose of viewing television. Introduced in the late 1920s in mechanical form, television sets became a popular consumer product after World War II in electronic form, using cathode ray tubes. The addition of color to broadcast television after 1953 further increased the popularity of television sets in the 1960s, and an outdoor antenna became a common feature of suburban homes.', 299.50, 'USD', 5, '/ec9d44660f0d4b1c957cd3f7cb9e723a.jpg');
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION, PRICE, PRICE_UNIT, CATEGORY_ID, IMAGE_PATH) VALUES ('Gorizont', 'A television set, more commonly called a television, TV, TV set, television receiver, or telly, is a device that combines a tuner, display, and loudspeakers for the purpose of viewing television. Introduced in the late 1920s in mechanical form, television sets became a popular consumer product after World War II in electronic form, using cathode ray tubes. The addition of color to broadcast television after 1953 further increased the popularity of television sets in the 1960s, and an outdoor antenna became a common feature of suburban homes.', 99999.99, 'USD', 5, '/40cb49854fe343d695d722667e2da185.jpg');