CREATE TABLE ROLES
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME NCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX "roles_name_uindex" ON ROLES (NAME);

CREATE TABLE USERS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  LOGIN NCHAR(50) NOT NULL,
  PASSWORD NCHAR(50) NOT NULL,
  FIRST_NAME NCHAR(255) NOT NULL,
  LAST_NAME NCHAR(255) NOT NULL,
  ROLE INTEGER,
  ACCOUNT DECIMAL(11,2) NOT NULL,
  ACCOUNT_UNIT NCHAR(3) NOT NULL,
  ADDRESS NCHAR(255),
  CONSTRAINT USERS_ROLES_ID_FK FOREIGN KEY (ROLE) REFERENCES ROLES (ID)
);
CREATE UNIQUE INDEX "users_login_uindex" ON USERS (LOGIN);

INSERT INTO ROLES VALUES (1,'Anonymous');
INSERT INTO ROLES VALUES (2,'User');
INSERT INTO ROLES VALUES (3,'Administrator');
INSERT INTO USERS VALUES (DEFAULT, 'hello','world','Max','Last Name',3,0.0,'USD','address');

CREATE TABLE ORDER_STATUS
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAME NCHAR(255)
);

INSERT INTO ORDER_STATUS VALUES (1,'Processing');
INSERT INTO ORDER_STATUS VALUES (2,'Shipping');
INSERT INTO ORDER_STATUS VALUES (3,'Completed');

CREATE TABLE CATEGORIES
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME NCHAR(255) NOT NULL,
  DESCRIPTION NTEXT NULL
);
CREATE UNIQUE INDEX "CATEGORIES_NAME_uindex" ON PUBLIC.CATEGORIES (NAME);

CREATE TABLE PRODUCTS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME NCHAR(255) NOT NULL,
  DESCRIPTION NTEXT,
  PRICE DECIMAL(11,2) NOT NULL,
  PRICE_UNIT NCHAR(3) NOT NULL,
  CATEGORY_ID INT NULL,
  IMAGE_PATH NCHAR(255),
  CONSTRAINT PRODUCTS_CATEGORIES_ID_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID)
);
CREATE UNIQUE INDEX "products_name_uindex" ON PRODUCTS (NAME);


CREATE TABLE ORDERS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CART_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  TIME TIMESTAMP NOT NULL,
  TOTAL DECIMAL(11,2) NOT NULL,
  TOTAL_UNIT NCHAR(3) NOT NULL,
  ORDER_STATUS INTEGER NOT NULL,
  CONSTRAINT ORDERS_ORDER_STATUS_ID_FK FOREIGN KEY (ORDER_STATUS) REFERENCES ORDER_STATUS (ID),
  CONSTRAINT ORDERS_USERS_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT ORDERS_CART_ID_FK FOREIGN KEY (CART_ID) REFERENCES CARTS (ID)
);

CREATE TABLE PUBLIC.carts
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
);

CREATE TABLE CART_TO_PRODUCTS
(
  CART_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL,
  CONSTRAINT CART_TO_PRODUCTS_CART_ID_FK FOREIGN KEY (CART_ID) REFERENCES CARTS (ID),
  CONSTRAINT CART_TO_PRODUCTS_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);

